# Generated by Django 5.1.7 on 2025-03-25 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='описание будет добавлено позднее', max_length=500),
        ),
    ]
